name: .NET Core

on: 
  push:
    branches: 
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Pack
      run: dotnet pack --configuration Release
    - name: publish Core to GitHub
      run: dotnet nuget push "Stasistium.Core/bin/Release/*.nupkg" --source "https://nuget.pkg.github.com/LokiMidgard/index.json" -k ${{ secrets.GITHUB_TOKEN }}
    - name: publish Razor to GitHub
      run: dotnet nuget push "Stasistium.Razor/bin/Release/*.nupkg" --source "https://nuget.pkg.github.com/LokiMidgard/index.json" -k ${{ secrets.GITHUB_TOKEN }}
    - name: publish YAML to GitHub
      run: dotnet nuget push "Stasistium.YAML/bin/Release/*.nupkg" --source "https://nuget.pkg.github.com/LokiMidgard/index.json" -k ${{ secrets.GITHUB_TOKEN }}
    - name: publish Markdown to GitHub
      run: dotnet nuget push "Stasistium.Markdown/bin/Release/*.nupkg" --source "https://nuget.pkg.github.com/LokiMidgard/index.json" -k ${{ secrets.GITHUB_TOKEN }}
    - name: publish Git to GitHub
      run: dotnet nuget push "Stasistium.Git/bin/Release/*.nupkg" --source "https://nuget.pkg.github.com/LokiMidgard/index.json" -k ${{ secrets.GITHUB_TOKEN }}
